FROM tomcat:9.0.16-jre8

MAINTAINER Yishan Xu
ARG APP_ENV=test
ENV APP_ENV ${APP_ENV}

ENV PROFILES=${PROFILES}
ENV DB_SERVERNAME=${SERVERNAME}
ENV DB_USERNAME=${USERNAME}
ENV DB_PASSWORD=${PASSWORD}



EXPOSE 8080

RUN rm -rf /usr/local/tomcat/webapps/ROOT
COPY ./*.war /usr/local/tomcat/webapps/ROOT.war
COPY ./setenv.${APP_ENV}.sh /usr/local/tomcat/bin/setenv.sh