ALTER TABLE users
	ADD COLUMN acc_locker BOOLEAN DEFAULT TRUE;
ALTER TABLE users
  ADD COLUMN acc_expired BOOLEAN DEFAULT TRUE;
ALTER TABLE users
  ADD COLUMN cred_expired BOOLEAN DEFAULT TRUE;
ALTER TABLE users
  ADD COLUMN is_enabled BOOLEAN DEFAULT TRUE;
